# 데이터 전처리 방법 실습

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## 데이터 로딩 및 DataFrame 만들기

In [11]:
df = pd.read_csv("./datas_ml/Data.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [ ]:
# 온라인 소핑목 고객 데이터라고 가정, 이 소핑목에서 물건을 구매했으면, Purchased 가 yes
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [5]:
df['Purchased'].value_counts()

Purchased
No     5
Yes    5
Name: count, dtype: int64

In [6]:
df['Country'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

## 결측치(NaN) 확인

In [7]:
df.isna()

Country    Age  Salary  Purchased
0    False  False   False      False
1    False  False   False      False
2    False  False   False      False
3    False  False   False      False
4    False  False    True      False
5    False  False   False      False
6    False   True   False      False
7    False  False   False      False
8    False  False   False      False
9    False  False   False      False

In [8]:
df.isna().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

### 결측치 처리 방법
-1 제거

In [14]:
#NaN이 있는 행 제거.
df.dropna()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
5   France  35.0  58000.0       Yes
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [15]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

- 채우기 전략

In [16]:
# NaN -> 0 or Mean, Mode .... 

df.fillna(0)

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      0.0       Yes
5   France  35.0  58000.0       Yes
6    Spain   0.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [17]:
df.fillna(df['Age'].mean())

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000     38.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [18]:
df.fillna(df.mean(numeric_only=True))

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [19]:
df= df.dropna()
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
5   France  35.0  58000.0       Yes
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [21]:
# index 초기화
df.reset_index(drop=True)

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4   France  35.0  58000.0       Yes
5   France  48.0  79000.0       Yes
6  Germany  50.0  83000.0        No
7   France  37.0  67000.0       Yes

## x, y 데이터 분리

In [22]:
# x는 독립변수, y는 종속변수
y = df['Purchased']
y

0     No
1    Yes
2     No
3     No
5    Yes
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [23]:
x = df.loc[:,'Country':'Salary']
x

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
5   France  35.0  58000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

## 레이블 인코딩, one hot encoding
- 범주형 데이터를 숫자로 변환
- 레이블 인코딩 : 문자열 -> 0,1,2,...
- One Hot encoding : 

## 레이블 인코딩하는 방법

In [3]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [25]:
# 객체 생성
encoder = LabelEncoder()
encoder

LabelEncoder()

In [28]:
x['Country']

0     France
1      Spain
2    Germany
3      Spain
5     France
7     France
8    Germany
9     France
Name: Country, dtype: object

In [27]:
encoder.fit_transform(x['Country'])

array([0, 2, 1, 2, 0, 0, 1, 0])

## One Hot Encoding 하는 방법

In [ ]:
# from sklearn.compose import ColumnTransformer

In [ ]:
# ct = ColumnTransformer( [('encoder', OneHotEncoder(), [칼럼인덱스1, 칼럼인덱스2])] )
ct = ColumnTransformer( [('encoder', OneHotEncoder(), [0])] )

In [ ]:
# 변환(원핫인코딩으로)

ct.fit_transform(x)

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [36]:
x

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
5   France  35.0  58000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [44]:
ct = ColumnTransformer( [('encoder', OneHotEncoder(), [0])], remainder='passthrough' )
x = ct.fit_transform(x)

In [45]:
x

array([[1.0e+00, 0.0e+00, 0.0e+00, 4.4e+01, 7.2e+04],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.7e+01, 4.8e+04],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.0e+01, 5.4e+04],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.8e+01, 6.1e+04],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.5e+01, 5.8e+04],
       [1.0e+00, 0.0e+00, 0.0e+00, 4.8e+01, 7.9e+04],
       [0.0e+00, 1.0e+00, 0.0e+00, 5.0e+01, 8.3e+04],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.7e+01, 6.7e+04]])

## y데이터도 인코딩

In [39]:
y.value_counts()

Purchased
No     4
Yes    4
Name: count, dtype: int64

In [42]:
y=y.map({'No':0, 'Yes':1})

In [43]:
y

0    0
1    1
2    0
3    0
5    1
7    1
8    0
9    1
Name: Purchased, dtype: int64

In [ ]:

x[:5]

array([[1.0e+00, 0.0e+00, 0.0e+00, 4.4e+01, 7.2e+04],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.7e+01, 4.8e+04],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.0e+01, 5.4e+04],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.8e+01, 6.1e+04],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.5e+01, 5.8e+04]])

In [48]:
## x,y 인코딩 후, feature scaling 진행 필요.

## 피쳐스케일링

In [51]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [56]:
# 표준화(평균이 0, 분산이 1 따르는 정규분포를 따르는 범위 데이터로 변환)
# 객체생성
scaler = StandardScaler()

# 변환
x_scaled = scaler.fit_transform(x)

In [53]:
scaler = MinMaxScaler()
scaler.fit_transform(x)

array([[1.        , 0.        , 0.        , 0.73913043, 0.68571429],
       [0.        , 0.        , 1.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        , 0.13043478, 0.17142857],
       [0.        , 0.        , 1.        , 0.47826087, 0.37142857],
       [1.        , 0.        , 0.        , 0.34782609, 0.28571429],
       [1.        , 0.        , 0.        , 0.91304348, 0.88571429],
       [0.        , 1.        , 0.        , 1.        , 1.        ],
       [1.        , 0.        , 0.        , 0.43478261, 0.54285714]])

In [54]:
# 데이터 전처리한 것들
# 1. 결측치 처리
# 2. 데이터 분리
# 3. 인코딩 : 문자 > 숫자
# 4. 피처 스케일링 : 데이터 수준을 맞추기 위해. 독립변수만 진행)

## train, test 데이터 분할

In [57]:
x_scaled

array([[ 1.        , -0.57735027, -0.57735027,  0.69985807,  0.58989097],
       [-1.        , -0.57735027,  1.73205081, -1.51364653, -1.50749915],
       [-1.        ,  1.73205081, -0.57735027, -1.12302807, -0.98315162],
       [-1.        , -0.57735027,  1.73205081, -0.08137885, -0.37141284],
       [ 1.        , -0.57735027, -0.57735027, -0.47199731, -0.6335866 ],
       [ 1.        , -0.57735027, -0.57735027,  1.22068269,  1.20162976],
       [-1.        ,  1.73205081, -0.57735027,  1.48109499,  1.55119478],
       [ 1.        , -0.57735027, -0.57735027, -0.211585  ,  0.1529347 ]])

In [55]:
from sklearn.model_selection import train_test_split

In [58]:
# train : test -> 8 : 2
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y, test_size=0.25, random_state=42)

In [61]:
x_train, y_train

(array([[ 1.        , -0.57735027, -0.57735027,  0.69985807,  0.58989097],
        [ 1.        , -0.57735027, -0.57735027, -0.211585  ,  0.1529347 ],
        [-1.        ,  1.73205081, -0.57735027, -1.12302807, -0.98315162],
        [ 1.        , -0.57735027, -0.57735027, -0.47199731, -0.6335866 ],
        [-1.        , -0.57735027,  1.73205081, -0.08137885, -0.37141284],
        [-1.        ,  1.73205081, -0.57735027,  1.48109499,  1.55119478]]),
 0    0
 9    1
 2    0
 5    1
 3    0
 8    0
 Name: Purchased, dtype: int64)

# 자동차 판매 예측

In [4]:
df = pd.read_csv('datas_ml/cars.csv')
df

Brand    Model    Year   Mileage  EngineSize  FuelType  Color  \
0        Ford   Escape  2001.0  287486.0    4.800248    Diesel  Black   
1    Mercedes  E-Class  2014.0  168229.0    4.802429  Gasoline  White   
2    Mercedes  E-Class  2023.0  106081.0    3.293752  Gasoline    Red   
3         Kia  Sorento  2009.0   89045.0    3.527349  Gasoline    NaN   
4        Ford   Escape  2005.0   34698.0    2.793782    Hybrid  Black   
..        ...      ...     ...       ...         ...       ...    ...   
295      Ford    Focus  2017.0  178352.0    2.289415    Diesel  Black   
296       Kia  Sorento  2005.0   79459.0    4.239498    Hybrid  Black   
297   Hyundai   Tucson  2018.0  195004.0    2.018563  Gasoline   Gray   
298  Mercedes  C-Class  2021.0  200968.0    3.726011  Gasoline  Black   
299      Ford   Escape  2011.0   59163.0    4.040911  Gasoline    Red   

      Region            ConditionDesc SellerType  Price  
0    Daejeon                 like new     Dealer    580  
1      Seoul                      NaN     Dealer   1835  
2    Incheon             engine issue     Dealer   2226  
3      Daegu  minor scratch on bumper     Dealer   1050  
4      Seoul                      NaN    Private   1290  
..       ...                      ...        ...    ...  
295    Daegu              slight dent    Private   1166  
296    Busan           needs painting     Dealer   1045  
297    Seoul        no major problems     Dealer   1265  
298    Busan        no major problems     Dealer   1947  
299  Incheon             engine issue    Private   1489  

[300 rows x 11 columns]

In [5]:
df.shape

(300, 11)

In [6]:
df.isna().sum()

Brand             0
Model             0
Year             15
Mileage          20
EngineSize        0
FuelType          0
Color            10
Region            8
ConditionDesc    25
SellerType        0
Price             0
dtype: int64

In [7]:
df_clean = df.dropna().copy()
df_clean

Brand     Model    Year   Mileage  EngineSize  FuelType  Color  \
0        Ford    Escape  2001.0  287486.0    4.800248    Diesel  Black   
2    Mercedes   E-Class  2023.0  106081.0    3.293752  Gasoline    Red   
6        Ford  Explorer  2023.0   22671.0    2.314658        EV  Black   
8    Mercedes   E-Class  2001.0   51663.0    4.009498    Diesel   Gray   
9         BMW        X5  2020.0   15708.0    4.166316    Hybrid  Black   
..        ...       ...     ...       ...         ...       ...    ...   
295      Ford     Focus  2017.0  178352.0    2.289415    Diesel  Black   
296       Kia   Sorento  2005.0   79459.0    4.239498    Hybrid  Black   
297   Hyundai    Tucson  2018.0  195004.0    2.018563  Gasoline   Gray   
298  Mercedes   C-Class  2021.0  200968.0    3.726011  Gasoline  Black   
299      Ford    Escape  2011.0   59163.0    4.040911  Gasoline    Red   

      Region             ConditionDesc SellerType  Price  
0    Daejeon                  like new     Dealer    580  
2    Incheon              engine issue     Dealer   2226  
6      Daegu  regular maintenance done    Private   2058  
8    Daejeon          dashboard damage    Private   1371  
9      Busan       noise in suspension    Private   2342  
..       ...                       ...        ...    ...  
295    Daegu               slight dent    Private   1166  
296    Busan            needs painting     Dealer   1045  
297    Seoul         no major problems     Dealer   1265  
298    Busan         no major problems     Dealer   1947  
299  Incheon              engine issue    Private   1489  

[227 rows x 11 columns]

In [9]:
y = df_clean['Price']
y

0       580
2      2226
6      2058
8      1371
9      2342
       ... 
295    1166
296    1045
297    1265
298    1947
299    1489
Name: Price, Length: 227, dtype: int64

In [10]:
X = df_clean.drop('Price', axis=1)
X

Brand     Model    Year   Mileage  EngineSize  FuelType  Color  \
0        Ford    Escape  2001.0  287486.0    4.800248    Diesel  Black   
2    Mercedes   E-Class  2023.0  106081.0    3.293752  Gasoline    Red   
6        Ford  Explorer  2023.0   22671.0    2.314658        EV  Black   
8    Mercedes   E-Class  2001.0   51663.0    4.009498    Diesel   Gray   
9         BMW        X5  2020.0   15708.0    4.166316    Hybrid  Black   
..        ...       ...     ...       ...         ...       ...    ...   
295      Ford     Focus  2017.0  178352.0    2.289415    Diesel  Black   
296       Kia   Sorento  2005.0   79459.0    4.239498    Hybrid  Black   
297   Hyundai    Tucson  2018.0  195004.0    2.018563  Gasoline   Gray   
298  Mercedes   C-Class  2021.0  200968.0    3.726011  Gasoline  Black   
299      Ford    Escape  2011.0   59163.0    4.040911  Gasoline    Red   

      Region             ConditionDesc SellerType  
0    Daejeon                  like new     Dealer  
2    Incheon              engine issue     Dealer  
6      Daegu  regular maintenance done    Private  
8    Daejeon          dashboard damage    Private  
9      Busan       noise in suspension    Private  
..       ...                       ...        ...  
295    Daegu               slight dent    Private  
296    Busan            needs painting     Dealer  
297    Seoul         no major problems     Dealer  
298    Busan         no major problems     Dealer  
299  Incheon              engine issue    Private  

[227 rows x 10 columns]

## 문자열 데이터 처리

In [12]:
# 컬럼 삭제
X = X.drop('ConditionDesc', axis=1)
X

Brand     Model    Year   Mileage  EngineSize  FuelType  Color  \
0        Ford    Escape  2001.0  287486.0    4.800248    Diesel  Black   
2    Mercedes   E-Class  2023.0  106081.0    3.293752  Gasoline    Red   
6        Ford  Explorer  2023.0   22671.0    2.314658        EV  Black   
8    Mercedes   E-Class  2001.0   51663.0    4.009498    Diesel   Gray   
9         BMW        X5  2020.0   15708.0    4.166316    Hybrid  Black   
..        ...       ...     ...       ...         ...       ...    ...   
295      Ford     Focus  2017.0  178352.0    2.289415    Diesel  Black   
296       Kia   Sorento  2005.0   79459.0    4.239498    Hybrid  Black   
297   Hyundai    Tucson  2018.0  195004.0    2.018563  Gasoline   Gray   
298  Mercedes   C-Class  2021.0  200968.0    3.726011  Gasoline  Black   
299      Ford    Escape  2011.0   59163.0    4.040911  Gasoline    Red   

      Region SellerType  
0    Daejeon     Dealer  
2    Incheon     Dealer  
6      Daegu    Private  
8    Daejeon    Private  
9      Busan    Private  
..       ...        ...  
295    Daegu    Private  
296    Busan     Dealer  
297    Seoul     Dealer  
298    Busan     Dealer  
299  Incheon    Private  

[227 rows x 9 columns]

In [15]:
X.columns

Index(['Brand', 'Model', 'Year', 'Mileage', 'EngineSize', 'FuelType', 'Color',
       'Region', 'SellerType'],
      dtype='object')

In [13]:
# X 문자열 컬럼 2개인지, 3개 이상인지 확인
X['Brand'].nunique()

5

In [16]:
X['Model'].nunique()

20

In [17]:
X['FuelType'].nunique()

4

In [18]:
X['Color'].nunique()

6

In [19]:
X['Region'].nunique()

5

In [20]:
X['SellerType'].nunique()

2

## 인코딩할 칼럼 구분
- 레이블 인코딩 할 칼럼
- 원한 인코딩할 칼럼
- 숫자 데이터 -> 피처스케일링 해야함

In [21]:
X.head()

Brand     Model    Year   Mileage  EngineSize  FuelType  Color   Region  \
0      Ford    Escape  2001.0  287486.0    4.800248    Diesel  Black  Daejeon   
2  Mercedes   E-Class  2023.0  106081.0    3.293752  Gasoline    Red  Incheon   
6      Ford  Explorer  2023.0   22671.0    2.314658        EV  Black    Daegu   
8  Mercedes   E-Class  2001.0   51663.0    4.009498    Diesel   Gray  Daejeon   
9       BMW        X5  2020.0   15708.0    4.166316    Hybrid  Black    Busan   

  SellerType  
0     Dealer  
2     Dealer  
6    Private  
8    Private  
9    Private

In [22]:
X.columns

Index(['Brand', 'Model', 'Year', 'Mileage', 'EngineSize', 'FuelType', 'Color',
       'Region', 'SellerType'],
      dtype='object')

## 현업방법 - 데이터 전처리

In [24]:
label_cols = ['SellerType']
onehot_cols = ['Brand', 'Model', 'FuelType', 'Color', 'Region']
numeric_cols = [ 'Year', 'Mileage', 'EngineSize']

In [29]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [30]:
ct = ColumnTransformer([ ('label', OrdinalEncoder(), label_cols),
                   ('onehot', OneHotEncoder(), onehot_cols),
                   ('scaler', StandardScaler(), numeric_cols) ] )

In [31]:
ct

ColumnTransformer(transformers=[('label', OrdinalEncoder(), ['SellerType']),
                                ('onehot', OneHotEncoder(),
                                 ['Brand', 'Model', 'FuelType', 'Color',
                                  'Region']),
                                ('scaler', StandardScaler(),
                                 ['Year', 'Mileage', 'EngineSize'])])

In [32]:
# sparse matrix로 표현
print(ct.fit_transform(X))

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1917 stored elements and shape (227, 44)>
  Coords	Values
  (0, 2)	1.0
  (0, 11)	1.0
  (0, 26)	1.0
  (0, 30)	1.0
  (0, 38)	1.0
  (0, 41)	-0.9249768106545554
  (0, 42)	1.7880660195193743
  (0, 43)	1.5429197838977786
  (1, 5)	1.0
  (1, 10)	1.0
  (1, 28)	1.0
  (1, 33)	1.0
  (1, 39)	1.0
  (1, 41)	1.4354392304332764
  (1, 42)	-0.3546402183717234
  (1, 43)	0.2937526938363846
  (2, 0)	1.0
  (2, 2)	1.0
  (2, 12)	1.0
  (2, 27)	1.0
  (2, 30)	1.0
  (2, 37)	1.0
  (2, 41)	1.4354392304332764
  (2, 42)	-1.3398563221312474
  (2, 43)	-0.5180987553925732
  :	:
  (224, 3)	1.0
  (224, 23)	1.0
  (224, 28)	1.0
  (224, 32)	1.0
  (224, 40)	1.0
  (224, 41)	0.8989810392769509
  (224, 42)	0.6956939333439961
  (224, 43)	-0.7636173326615148
  (225, 5)	1.0
  (225, 9)	1.0
  (225, 28)	1.0
  (225, 30)	1.0
  (225, 36)	1.0
  (225, 41)	1.2208559539707462
  (225, 42)	0.7661390699321965
  (225, 43)	0.6521764959891053
  (226, 0)	1.0
  (226, 2)	1.0
  (226, 11)	1.0